// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZsMsG3QXVasxAH0t75s-YZKf5aprQPUY',
    appId: '1:1050253232665:web:4a81e042fe1f298c6c3888',
    messagingSenderId: '1050253232665',
    projectId: 'spotify-clone-e9eda',
    authDomain: 'spotify-clone-e9eda.firebaseapp.com',
    storageBucket: 'spotify-clone-e9eda.firebasestorage.app',
    measurementId: 'G-SNN05QK007',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO_vV6Yd8vpx1IHpAzcm5vM4SFeC3aS8A',
    appId: '1:1050253232665:android:5333058257f193836c3888',
    messagingSenderId: '1050253232665',
    projectId: 'spotify-clone-e9eda',
    storageBucket: 'spotify-clone-e9eda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPNU2_kZixSgSpc7Hyep3L2pyLnLber9Q',
    appId: '1:1050253232665:ios:4da8128848e6f7166c3888',
    messagingSenderId: '1050253232665',
    projectId: 'spotify-clone-e9eda',
    storageBucket: 'spotify-clone-e9eda.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPNU2_kZixSgSpc7Hyep3L2pyLnLber9Q',
    appId: '1:1050253232665:ios:4da8128848e6f7166c3888',
    messagingSenderId: '1050253232665',
    projectId: 'spotify-clone-e9eda',
    storageBucket: 'spotify-clone-e9eda.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZsMsG3QXVasxAH0t75s-YZKf5aprQPUY',
    appId: '1:1050253232665:web:b4f78085b4b0d41a6c3888',
    messagingSenderId: '1050253232665',
    projectId: 'spotify-clone-e9eda',
    authDomain: 'spotify-clone-e9eda.firebaseapp.com',
    storageBucket: 'spotify-clone-e9eda.firebasestorage.app',
    measurementId: 'G-VC1KJDRZCL',
  );
}
